version: '3.5'
services:
  # Servicio para MariaDB
  mariadb_cidenet:
    image: mariadb:bionic
    container_name: mariadb_cidenet
    environment:
      - MYSQL_DATABASE=cidenet
      - MYSQL_ROOT_PASSWORD=Gbd12345678;
      - MYSQL_USER=cidenet
      - MYSQL_PASSWORD=6e51In#/();*+
    volumes:
      - ./volumes/mysql:/var/lib/mysql/
    expose:
      - 3600
    ports:
      - 3600:3306
    restart: always
    networks:
      - network_cidenet

  #Servicio para PHPMyadmin
  phpmyadmin_cidenet:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_cidenet
    volumes:
      - ./volumes/phpmyadmin:/sessions/
    expose:
      - 8681
    ports:
      - 8681:80
    environment:
      - PMA_HOST=mariadb_cidenet
      - PMA_PORT=3306
    depends_on:
      - mariadb_cidenet
    restart: always
    networks:
      - network_cidenet

  # Servicio para PHP
  php_cidenet:
    build: .
    container_name: php_cidenet
    volumes:
      - ./:/var/www/html/
    expose:
      - 8006
    ports:
      - 8006:80
    links:
      - mariadb_cidenet
    restart: always
    networks:
      - network_cidenet

# Red del proyecto
networks:
  network_cidenet:
    name: network_cidenet